build: 
	gcc -pthread thread.c -o thread 
	gcc -pthread two-arguments.c -o two-arguments 
	gcc -pthread git cline parallelLineMultThreads.c -o parallelLineMultThreads
	gcc -pthread simple_threads.c -o simple_threads
	gcc -pthread exercise-4-17.c -o exercise-4-17

clean:
	rm -f thread two-arguments parallelLineMultThreads simple_threads exercise-4-17
